# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# This enables the 'defaults' to test java applications:
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images
jdk:
 - oraclejdk8
 - oraclejdk9

# Each job in Travis CI has several steps:
# https://docs.travis-ci.com/user/job-lifecycle/
# The 'language: java' directive sets up sane defaults to test common java applications
# We use the defaults for installing dependencies, compiling and testing maven applications
# In our case it will be 'mvn install' followed by 'mvn test'

# This is to enable CodeCov's coverage
# If a build is successful, the code is submitted for coverage analysis
after_success:
  - bash <(curl -s https://codecov.io/bash)
